[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://aib-aibchatbot.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
